Repository DEFRA/water-abstraction-import, pull requests merged in 2022-08, with the labels that each got.

#393 Update release process
  package.json
Labels: enhancement

#397 Hide `standard` linting commit with `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: enhancement, housekeeping

#398 Make cron background job timings configurable
  .env.example
  config.js
  test/modules/charging-import/plugin.js
  test/modules/licence-import/plugin.js
Labels: housekeeping

#400 Set log level using new env var
  .env.example
  config.js
Labels: housekeeping

#405 Correctly set NODE_ENV
  .env.example
  config.js
  src/lib/slack.js
  src/modules/core/jobs/import-tracker.js
  src/modules/nald-import/lib/persist-returns.js
  test/lib/plugin.js
  test/modules/charging-import/plugin.js
  test/modules/core/jobs/import-tracker.js
  test/modules/core/plugin.js
  test/modules/nald-import/plugin.js
Labels: housekeeping
