Repository DEFRA/water-abstraction-import, pull requests merged in 2022-12, with the labels that each got.

#496 Update water-abstraction-helpers to latest version
  package-lock.json
  package.json
  scripts/licence-creator/index.js
Labels: dependencies

#502 Fix issue with migrations
  database.json
Labels: bug

#505 Remove hapi good - add hapi-pino
  config.js
  index.js
  package-lock.json
  package.json
  src/lib/services/hapi-pino-ignore-request.service.js
  src/plugins/hapi-pino.plugin.js
  test/lib/services/hapi-pino-ignore-request.service.test.js
Labels: housekeeping

#507 Refactor HapiPinoIgnoreRequestService as module
  src/lib/services/hapi-pino-ignore-request.service.js
Labels: housekeeping

#519 Remove verbose from db migrate commands
  package.json
  scripts/migrate.js
Labels: housekeeping
