Repository DEFRA/water-abstraction-import, pull requests merged in 2023-06, with the labels that each got.

#647 Update `standard` package
  package-lock.json
  package.json
  scripts/licence-creator/condition-type.js
  scripts/licence-creator/rep-unit.js
  scripts/licence-creator/return-version.js
  src/lib/services/import.js
  src/modules/licence-import/connectors/queries/purpose-condition-types.js
  test/modules/licence-import/transform/data.js
Labels: housekeeping

#650 Update Hapi to v21
  index.js
  package-lock.json
  package.json
  test/modules/nald-import/nald.test.js
Labels: housekeeping

#648 Add web trigger for NALD import
  src/modules/nald-import/controller.js
  src/modules/nald-import/jobs/s3-download.js
  src/modules/nald-import/routes.js
Labels: enhancement

#651 Remove Slack integration
  .env.example
  src/lib/slack.js
  src/modules/bill-runs-import/lib/import.js
  src/modules/charging-import/lib/query-loader.js
  src/modules/core/jobs/import-tracker.js
  src/modules/nald-import/services/extract-service.js
  test/modules/charging-import/lib/query-loader.test.js
  test/modules/core/jobs/import-tracker.test.js
  test/modules/nald-import/services/extract-service.test.js
Labels: housekeeping

#656 Make hard coded job schedules configurable
  .env.example
  config.js
  src/modules/core/jobs/import-tracker.js
  src/modules/core/plugin.js
  src/modules/nald-import/plugin.js
  test/modules/core/jobs/import-tracker.test.js
  test/modules/core/plugin.test.js
  test/modules/nald-import/plugin.test.js
Labels: housekeeping

#658 Fix charging-import charge versions job
  src/modules/charging-import/lib/queries/charging.js
  src/modules/nald-import/lib/nald-queries/charge-versions.js
Labels: bug

#660 Alter fix for charge versions import
  src/modules/charging-import/jobs/charge-versions.js
  src/modules/charging-import/lib/queries/charging.js
  src/modules/nald-import/lib/nald-queries/charge-versions.js
Labels: bug

#665 Update log and errbit notifiers
  src/lib/notifiers/base-notifier.lib.js
  src/lib/notifiers/global-notifier.lib.js
  test/lib/notifiers/base-notifier.lib.test.js
  test/lib/notifiers/global-notifier.lib.test.js
Labels: housekeeping
