Repository DEFRA/water-abstraction-import, pull requests merged in 2024-10, with the labels that each got.

#1029 Import abstraction method for lic. purpose points
  src/modules/points/jobs/licences.js
Labels: housekeeping

#1030 Clean up return reqs. linked to void return logs
  src/modules/return-versions/lib/clean-queries.js
Labels: housekeeping

#1033 Fix broken crm_v2.documents constraint
  src/modules/licence-import/load/connectors/queries.js
Labels: bug

#1034 Refactor `licence-document` clean job
  src/modules/licence-import/connectors/documents.js
  src/modules/licence-import/connectors/queries/clean-queries.js
  src/modules/licence-import/controller.js
  src/modules/licence-import/jobs/clean.js
  src/modules/licence-import/plugin.js
  test/modules/licence-import/connectors/documents.test.js
  test/modules/licence-import/controller.test.js
  test/modules/licence-import/jobs/clean.test.js
  test/modules/licence-import/plugin.test.js
Labels: housekeeping

#1035 Cleanup `licence_version_purpose_conditions` table
  src/modules/licence-import/connectors/queries/clean-queries.js
  src/modules/licence-import/jobs/clean.js
Labels: enhancement

#1036 Cleanup `licence_version_purposes` table
  src/modules/licence-import/connectors/queries/clean-queries.js
  src/modules/licence-import/jobs/clean.js
Labels: enhancement
