Repository DEFRA/water-abstraction-import, pull requests merged in 2024-06, with the labels that each got.

#942 Include NALD point ID in return reqs import
  src/modules/charging-import/lib/queries/return-versions.js
Labels: housekeeping

#948 Fix return req frequency fields being imported
  src/modules/charging-import/lib/queries/return-versions.js
Labels: bug

#949 Transform return version status to WRLS style
  src/modules/charging-import/jobs/charging-data.js
  src/modules/charging-import/lib/queries/return-versions.js
  test/modules/charging-import/jobs/charging-data.test.js
Labels: enhancement

#950 Set to 'draft' ret. versions with no requirements
  src/modules/charging-import/jobs/charging-data.js
  src/modules/charging-import/lib/queries/return-versions.js
  test/modules/charging-import/jobs/charging-data.test.js
Labels: enhancement

#954 Add missing return version end dates during import
  src/modules/charging-import/jobs/charging-data.js
  src/modules/charging-import/lib/queries/return-versions.js
  test/modules/charging-import/jobs/charging-data.test.js
Labels: enhancement

#961 Stop using version in package.json
  src/modules/health/controller.js
  test/modules/health/controller.test.js
Labels: housekeeping
