Repository DEFRA/water-abstraction-import, pull requests merged in 2024-11, with the labels that each got.

#1037 Cleanup `licence_versions` table
  src/modules/licence-import/connectors/queries/clean-queries.js
  src/modules/licence-import/jobs/clean.js
Labels: enhancement

#1038 Cleanup `licences` table
  src/modules/licence-import/connectors/queries/clean-queries.js
  src/modules/licence-import/jobs/clean.js
Labels: enhancement

#1040 Add Clean Licence feature flag to config
  config.js
  src/modules/licence-import/jobs/clean.js
Labels: enhancement

#1041 Clean up return reqs. linked to due return logs
  src/modules/return-versions/lib/clean-queries.js
Labels: housekeeping

#1042 Fix invalid return version clean query change
  src/modules/return-versions/lib/clean-queries.js
Labels: bug

#1043 Upgrade node to v22
  .nvmrc
  package.json
Labels: enhancement

#1046 Handle amended licence refs in rtn versions import
  src/modules/return-versions/lib/import-queries.js
Labels: bug

#1044 Delete "licences" that are not in NALD
  src/modules/licence-import/connectors/queries/clean-queries.js
  src/modules/licence-import/jobs/clean.js
Labels: enhancement
