Repository DEFRA/water-abstraction-import, pull requests merged in 2025-05, with the labels that each got.

#1095 Update returns import to bulk insert return logs
  src/modules/licence-returns-import/lib/persist-returns.js
  test/modules/licence-returns-import/lib/persist-returns.test.js
Labels: housekeeping

#1097 Include return logs with deleted rtn reqs in clean
  src/modules/invalid-returns-cleanup/lib/clean-no-requirement.js
  src/modules/invalid-returns-cleanup/process.js
Labels: enhancement

#1099 Fix "Build Status" badge
  README.md
Labels: documentation

#1100 Filter out submissions imported from NALD in API
  src/modules/returns/lib/api-helpers.js
  test/modules/returns/lib/api-helpers.test.js
Labels: bug, housekeeping

#1102 Change user id for imported return submissions
  src/modules/licence-submissions-import/lib/replicate-submissions.js
  src/modules/returns/lib/api-helpers.js
  test/modules/returns/lib/api-helpers.test.js
Labels: bug

#1103 Fix NALD received only rtns in WRLS for last cycle
  src/modules/clean/process.js
  src/modules/invalid-returns-cleanup/lib/clean-received-only.js
  src/modules/invalid-returns-cleanup/process.js
Labels: bug
